-- AlterTable
ALTER TABLE "User" ADD COLUMN     "likedPlaces" TEXT[],
ADD COLUMN     "weightInterest" DOUBLE PRECISION NOT NULL DEFAULT 30.0,
ADD COLUMN     "weightPreference" DOUBLE PRECISION NOT NULL DEFAULT 30.0,
ADD COLUMN     "weightTransit" DOUBLE PRECISION NOT NULL DEFAULT 40.0;
